# Generated by Django 5.0.1 on 2024-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=1500)),
                ('last_name', models.CharField(max_length=1500)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
